src/test/java/pages/home/brands_scrolling_list/BenefitPage.java, src/test/java/pages/home/brands_scrolling_list/BvlgariPage.java, src/test/java/pages/home/brands_scrolling_list/CalvinKleinPage.java, src/test/java/pages/home/brands_scrolling_list/DovePage.java, src/test/java/pages/home/brands_scrolling_list/GiorgioArmaniPage.java, src/test/java/pages/home/brands_scrolling_list/GucciPage.java, src/test/java/pages/home/brands_scrolling_list/LancomePage.java, src/test/java/pages/home/brands_scrolling_list/MacPage.java, src/test/java/pages/home/brands_scrolling_list/PantenePage.java, src/test/java/pages/home/brands_scrolling_list/SephoraPage.java, src/test/java/tests/home/brands_scrolling_list/BenefitTest.java, src/test/java/tests/home/brands_scrolling_list/BvlgariTest.java, src/test/java/tests/home/brands_scrolling_list/DoveTest.java, src/test/java/tests/home/brands_scrolling_list/GiorgioArmaniTest.java, src/test/java/tests/home/brands_scrolling_list/GucciTest.java, src/test/java/tests/home/brands_scrolling_list/KalvinKleinTest.java, src/test/java/tests/home/brands_scrolling_list/LancomeTest.java, src/test/java/tests/home/brands_scrolling_list/MacTest.java, src/test/java/tests/home/brands_scrolling_list/PanteneTest.java, src/test/java/tests/home/brands_scrolling_list/SephoraTest.java
Created Brands Scrolling List pages and added to tests
=> Created Brands Scrolling List pages and added to tests

src/test/java/pages/base_abstract/BasePage.java, src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/makeup/CheeksPage.java, src/test/java/tests/makeup/CheeksTest.java
testProductPriceTagChangedWhenAddedToCart() created on CheeksTest and methods added on Base, Main and Cheeks Pages
=> testProductPriceTagChangedWhenAddedToCart()

src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/product_list/ProductDescriptionPage.java, src/test/java/pages/product_list/benefit/BenefitBellaBambaPage.java, src/test/java/pages/product_list/benefit/BenefitGirlMeetsPearlPage.java, src/test/java/pages/product_list/books/AudioCDNewFrenchWithEasePage.java, src/test/java/pages/product_list/books/PaperbackAllegiantByVeronicaRothPage.java, src/test/java/pages/product_list/bvlgari/BvlgariPourHommeEauDeToilettePage.java, src/test/java/pages/product_list/calvin_klein/CKOneShockForHimDeodorantPage.java, src/test/java/pages/product_list/calvin_klein/CKSecretObsessionPerfumePage.java, src/test/java/pages/product_list/dove/DoveMenCareCleanComfortDeodorantPage.java, src/test/java/pages/product_list/giorgio_armani/GiorgioArmaniCodePourFemmePage.java, src/test/java/pages/product_list/gucci/GucciGuiltyPage.java, src/test/java/pages/product_list/lancome/LancomeTropiquesMineraleLooseBronzerPage.java, src/test/java/pages/product_list/mac/MacSkinsheenBronzerStickPage.java, src/test/java/pages/product_list/pantene/PanteneCurlsToStraightShampooPage.java, src/test/java/pages/product_list/pantene/PanteneHighlightingExpressionsPage.java, src/test/java/pages/product_list/sephora/SephoraSeaweedConditionerPage.java
added locators and Generics methods for ProductDescriptionPage
[US][Structure] - https://trello.com/b/oeN0DA8C/automationteststore
=> [US][Structure][ProductDescriptionPage] locators and methods for page <AleksandrAkimovChg>

pom.xml
testNG up to 7.7.1
[US][Structure] - https://trello.com/c/zQEEE8RA/15-usstructure-testng-update-to-version-771-aleksandrakimovchg
=> [US][Structure] TestNG update to version 7.7.1. <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/tests/makeup/CheeksTest.java
locators for Categorymenu been modified on ManePage and some methods renamed
=> [RF] [ManePage] [Categorymenu] Locators modified

src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/men/MenPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/men/MenTest.java
added testNavigatesToMen_ID58_Page
[US] - https://trello.com/c/6hs6abqZ/22-usfunctionalhometopmenumentestnavigatestomenid58pagemaxiasko
[TC] - https://trello.com/c/zkY0HOO7/23-tcfunctionalhometopmenumentestnavigatestomenid58pagemaxiasko
[AT] - https://trello.com/c/wu49gmFK/24-atfunctionalhometopmenumentestnavigatestomenid58pagemaxiasko
=> [US][Functional][Home][TopMenu][Men]testNavigatesToMen_ID58_Page<MaxIasko>

src/test/java/pages/base_abstract/MainPage.java
clickSkincareMenu() method modified in MainPage
[RF] - https://trello.com/c/W4C60Fjx/35-rfmainpage-clickskincaremenu-method-modified-natalliaowl
=> [RF][MainPage] clickSkincareMenu() method modified <NatalliaOwl>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/TestData.java, src/test/java/tests/MainTest.java
Created testBrandsScrollingListLinksNavigateToCorrespondingPages(), methods and loc added
[TC] - https://trello.com/c/f1lslkOU/33-tchomebrandsscrollinglistlinks-verify-using-the-dataprovider-that-all-brandsscrollinglist-links-go-to-the-correct-corresponding
[AT] - https://trello.com/c/xTIlKuYV/34-athomebrandsscrollinglistlinks-testbrandsscrollinglistlinksnavigatetocorrespondingpagesnataliiaoliver
=> [AT][Home][BrandsScrollingList][Links] testBrandsScrollingListLinksNavigateToCorrespondingPages<NataliiaOliver>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/tests/MainTest.java
Refactoring testBrandsScrollingListLinksNavigateToCorrespondingPages,  chenged method clickNavPillsCategoryMenu(int index)to clickMenu(int index, List<WebElement> menus)
[RF] - https://trello.com/c/sivBY21Q/38-rfhomebrandsscrollinglistlinks-testbrandsscrollinglistlinksnavigatetocorrespondingpagesnataliiaoliver
=> [RF][Home][BrandsScrollingList][Links] testBrandsScrollingListLinksNavigateToCorrespondingPages<NataliiaOliver>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/tests/home/HomeTest.java, src/test/java/tests/makeup/CheeksTest.java
created testDropdownSubmenuNamesOnCategoryHomeMenu() and testFourCategoriesOfDropdownSubmenuNamesOnCategoryHomeMenu(), locator and methods added
[TC] - https://trello.com/c/zz9PJ7Hx/39-tcmaincategorymenuhomesubmenulistsubmenu-verify-that-the-dropdown-submenu-on-categoryhomemenu-contains-4-categories-nataliiaoliv
[AT] - https://trello.com/c/73yqC4qp/44-at-testdropdownsubmenunamesoncategoryhomemenu-nataliiaoliver
=> [AT][Main][CategoryMenu][Home][Submenu][ListSubmenu] testDropdownSubmenuNamesOnCategoryHomeMenu() <NataliiaOliver>

src/test/java/pages/apparel_and_accessories/ApparelAndAccessoriesPage.java, src/test/java/pages/apparel_and_accessories/TShirtsPage.java, src/test/java/pages/base_abstract/MainPage.java, src/test/java/tests/apparel_and_accessories/TShirtsTest.java
[US] - https://trello.com/c/jtAM1sBK/42-usfunctional-apparel-accessoriest-shirts-sort-item-by-az-and-za-aramh20
[AT] - https://trello.com/c/A3sUKhF2/45-attcfunctional-apparel-accessoriest-shirts-sort-item-by-az-and-za-aramh20
[TC] - https://trello.com/c/7vmWjNlX/43-tcfunctional-apparel-accessoriest-shirts-sort-item-by-az-and-za-aramh20
=> [AT][TC][Functional][ Apparel & accessories][T-shirts] Sort item By AZ and ZA <AramH20>

src/test/java/pages/apparel_and_accessories/ApparelAndAccessoriesPage.java, src/test/java/pages/apparel_and_accessories/TShirtsPage.java, src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/pages/product_list/WomensStilettoSandals_ID118_Page.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/product_list/NewLadies_Sandals_ID116_Test.java, src/test/java/tests/product_list/WomensStilettoSandals_ID118_Test.java
refactored locators and methods on abstract product page
[US][Structure] - https://trello.com/c/DITlv31o/46-usstructureproductspage-refactored-locators-and-methods-on-abstract-product-page-aleksandrakimovchg
--------------------------------------------
added testNavigatesToWomensStilettoSandals_ID118_Page()
[US] - https://trello.com/c/oIeLi6Oj/19-usfunctionalmainproductpage-user-navigate-to-the-product-page-aleksandrakimovchg
[TC] - https://trello.com/c/RvjlsPFO/48-tcmainapparelaccessoriespagewomenshighheelpointtoestilettosandalsanklestrapcourtshoes-id118-navigate-to-womenshighheelpointtoest
[AT] - https://trello.com/c/z6JRRt9f/47-atmainapparelaccessoriespagewomenshighheelpointtoestilettosandalsanklestrapcourtshoes-id118-navigate-to-womenshighheelpointtoest
=> [US][Structure][ProductsPage] refactored locators and methods on abstract product page <AleksandrAkimovChg>

src/test/java/pages/SearchPage.java, src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/SearchTest.java
added testSearchProductByName()
added SearchPage, methods and locators created
[US] - https://trello.com/c/Wzs6m7wj/49-usfunctionalmainsearchpage-searchproductmaxiasko
[TC] - https://trello.com/c/1lWfQrQN/50-tcfunctionalmainsearchpagetestsearchproductbynamemaxiasko
[AT] - https://trello.com/c/JH2w9KTu/51-atfunctionalmainsearchpage-testsearchproductbynamemaxiasko
=> [AT][Functional][Main][SearchPage] testSearchProductByName<MaxIasko>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/home/HomePage.java, src/test/java/testData/TestData.java, src/test/java/tests/home/HomeTest.java
testTopMenuLinksNavigateToCorrespondingPages() added
branch name is incorrect - was testing Top Menu Links (except 'Login or Register') using DataProvider
[TC] - https://trello.com/c/Xe5SJvsS/52-tchometopmenu-verify-topmenu-links-go-to-correct-corresponding-pages-using-dataprovider-nstzya
[AT] - https://trello.com/c/pCN1p4cg/53-athometopmenulinks-testtopmenulinksnavigatetocorrespondingpagesnstzya
=> [AT][Home][TopMenu][Links] testTopMenuLinksNavigateToCorrespondingPages<Nstzya>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/tests/skincare/SkincareTest.java
3 navigation tests for my "portion" of submenus in Skincare menu
Gift Ideas & Sets
[TC] - https://trello.com/c/n9NokNy1/58-tcmainskincaregiftideasandsets-clicking-on-gift-ideas-sets-submenu-navigates-to-id4345-page-veryfes
[AT] - https://trello.com/c/ayKCf4De/55-atmainskincaregiftideasandsets-testgiftideasandsetssubmenulinknavigatestoid4345page-verafes
Hands & Nails
[TC] - https://trello.com/c/8lgkNScz/59-tcmainskincarehands-nails-clicking-on-hands-nails-submenu-navigates-to-id4345-page-veryfes
[AT] - https://trello.com/c/DuQUJp9H/56-atmainskincarehandsandnails-testhandsandnailssubmenulinknavigatestoid4348page-verafes
Sun
[TC] - https://trello.com/c/GAOHyB8T/60-atmainskincaresun-clicking-on-sun-submenu-navigates-to-id4345-page-veryfes
[AT] - …
=> [TC][Main][Skincare][Submenus] Test navigation 3 skincare submenus <veryfes>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/apparel_and_accessories/TShirtsTest.java, src/test/java/tests/books/PaperbackTest.java
Created testProductListSortByAZ(), created paperback products list on ProgectConstans, added methods for the test on MainPage
[TC] - https://trello.com/c/JcHoLqnt/63-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-in-alphabetic-order-from-a-to-z-nataliiaoliver
[AT] - https://trello.com/c/nartDJOf/71-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbyaz-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByAZ() <NataliiaOliver>

src/test/java/tests/books/PaperbackTest.java
[TC] - https://trello.com/c/ku5KjLet/64-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-in-reverse-alphabetic-order-from-z-to-a-nataliiaoli
[AT] - https://trello.com/c/5jpwu52P/72-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbyza-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByZA () <NataliiaOliver>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/apparel_and_accessories/ShoesTest.java
added test for Shoes page testProductListSortByAZ()
[US] - https://trello.com/c/VbCIYI6c/75-usfunctionalmainnavmenuapparel-accessoriessubmenu-dropdownshoes-verify-product-sorting-in-alphabetic-order-from-a-to-a-aleksandr
[TC] - https://trello.com/c/tQ8e2zbj/74-tcfunctionalmainnavmenuapparel-accessoriessubmenu-dropdownshoes-verify-product-sorting-in-alphabetic-order-from-a-to-z-aleksandr
[AT] - https://trello.com/c/U0Cbutst/73-atfunctionalmainnavmenuapparel-accessoriessubmenu-dropdownshoes-testproductlistsortbyaz-aleksandrakimovchg
=> [AT][Functional][Main][NavMenu][Apparel & accessories][Submenu dropdown][Shoes] testProductListSortByAZ() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/tests/apparel_and_accessories/TShirtsTest.java
[US] - https://trello.com/c/P4h8t4Bf/80-usfunctional-apparel-accessoriest-shirts-sort-item-by-low-to-high-and-high-to-low-aramh20
[TC] - https://trello.com/c/IgmVOtE6/81-tcfunctional-apparel-accessoriest-shirts-sort-item-by-low-to-high-and-high-to-low-aramh20
[AT] - https://trello.com/c/8F2asFQZ/82-atfunctional-apparel-accessoriest-shirts-sort-item-by-low-to-high-and-high-to-low-aramh20
=> test_apparelAndAccessories_T-shirts_SortBy_ LowtoHigh_and_ HightoLow <AramH20>

src/test/java/testData/TestData.java, src/test/java/tests/MainTest.java
testTopMenuLinksNavigateToCorrespondingPages() refactored with log in scenario
[RF] - https://trello.com/c/edG0B7Ep/83-rfhometopmenulinks-testtopmenulinksnavigatetocorrespondingpagesnstzya
=> [RF][Home][TopMenu][Links] testTopMenuLinksNavigateToCorrespondingPages<Nstzya>

src/test/java/tests/apparel_and_accessories/ShoesTest.java
refactored testProductListSortByAZ()
[RF] - https://trello.com/c/qr7I7Rh9/84-rffunctionalmainnavmenuapparel-accessoriessubmenu-dropdownshoes-testproductlistsortbyaz-aleksandrakimovchg
=> [RF][Functional][Main][NavMenu][Apparel & accessories][Submenu dropdown][Shoes] testProductListSortByAZ() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/home/cart/CartTest.java
test Click on Cart button in LeftNavTop Navigates to Shopping Cart added
new ProjectConstants added: CART_PAGE_URL 
along with Cart Button XPath used  in the test, several more XPathes were added for Currency and Cart menu 
[TC] - https://trello.com/c/ol9stK4s/88-tcmainleftnavtopcartmenu-click-cart-button-in-left-nav-topcart-menu-navigates-to-shoppting-cart-verafes
[AT] - https://trello.com/c/GyDvBRsG/87-atmainleftnavtopcartmenu-testclickleftnavtopcartlinknavigatestocart-verafes
=> [AT][Main][LeftNavTopCartMenu] testClickLeftNavTopCartLink_NavigatesToCart() added

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/makeup/CheeksTest.java
ATFunctionalMainNavMen]MakeupSubmenuDropdownCheeksTestCheeksProductListSortByAZ_And_ByZA_AnzhelikaBaa added.
TC][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Cheeks] Verify if products sorted by name in alphabetical order from A to Z when click on Name A - Z dropdown submenu - https://trello.com/c/LYaBicWE/78-tcfunctionalmainnavmenumakeupsubmenudropdowncheeks-verify-if-products-sorted-by-name-in-alphabetical-order-from-a-to-z-when-clic
[AT][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Cheeks]testCheeksProductListSortByAZ - https://trello.com/c/FUC61w9x/89-atfunctionalmainnavmenumakeupsubmenudropdowncheekstestcheeksproductlistsortbyazanzhelikabaa
[TC][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Cheeks] Verify if products sorted by name in reverse order from Z to A …
=> [AT][Functional][Main][NavMen][MakeupSubmenuDropdown]TestsCheeksProductListSortByAZ_And_ByZA_AnzhelikaBaa

src/test/java/pages/SearchPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/SearchTest.java
[RF] - https://trello.com/c/XrQAZRjK/94-rffunctionalmainsearchpage-testsearchproductbynamemaxiasko
method location changed
=> [RF][Functional][Main][SearchPage] testSearchProductByName<MaxIasko>

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/apparel_and_accessories/ShoesTest.java, src/test/java/tests/product_list/NewLadies_Sandals_ID116_Test.java
added testNavigatesToShoesPage() and testProductListSortByZA()
-----
[US] - https://trello.com/c/pTPOiQ5T/92-usfunctionalmainshoespage-navigate-to-product-category-page-aleksandrakimovchg
[TC] - https://trello.com/c/QUSsfODC/91-tcmainnavmenuapparel-accessorieshoespage-navigate-to-shoes-page-aleksandrakimovchg
[AT] - https://trello.com/c/F6psjuiO/93-atmainnavmenuapparel-accessorieshoespage-added-testnavigatestoshoespage-aleksandrakimovchg
-----
[US] - https://trello.com/c/VbCIYI6c/75-usfunctionalmainnavmenuapparel-accessoriessubmenu-dropdownshoes-verify-product-sorting-in-alphabetic-order-from-a-to-a-aleksandr
[TC] - https://trello.com/c/igKiYn9y/85-tcmainnavmenuapparel-accessoriessubmenu-dropdownshoes-verify-product-sorting-in-alphabetic-order-from-z-to-a-aleksandrakimovchg
[AT] - …
=> [AT][Main][NavMenu][Apparel & accessories][Submenu dropdown][Shoes] testProductListSortByZA() <AleksandrAkimovChg>

src/test/java/pages/apparel_and_accessories/TShirtsPage.java, src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/tests/books/PaperbackTest.java
Created testProductListSortByPriceLowHigh()
[TC] - https://trello.com/c/zDYp360F/65-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-by-price-low-to-high-nataliiaoliver
[AT] - https://trello.com/c/5sS8RYK7/100-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbypricelowhigh-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByPriceLowHigh() <NataliiaOliver>

src/test/java/tests/books/PaperbackTest.java
Created testProductListSortByPriceHighLow()
[TC] - https://trello.com/c/40CAb6Zf/66-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-by-price-high-to-low-nataliiaoliver
[AT] - https://trello.com/c/C5NlWDx7/101-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbypricehighlow-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByPriceHighLow() <NataliiaOliver>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/skincare/SkincareTest.java
testEyesSubmenuLink_NavigatesToEyesPage() added
[TC] - https://trello.com/c/ZGZM6812/99-tcmainskincareeyes-verify-that-the-eyes-submenu-link-from-the-skincare-dropdown-menu-is-clickable-and-navigates-to-eyes-page-nat
[AT] - https://trello.com/c/BJdxu6Jf/103-atmainskincareeyes-testeyessubmenulinknavigatestoeyespage-natalliaowl
=> [AT][Main][Skincare][Eyes] testEyesSubmenuLink_NavigatesToEyesPage() <NatalliaOwl>

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/tests/books/PaperbackTest.java
Created testProductListSortByPriceLowHigh_V2() with bubbleSortDoubleArray() method
[TC] - https://trello.com/c/zDYp360F/65-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-by-price-low-to-high-nataliiaoliver
[AT] - https://trello.com/c/VgnH2OE9/104-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbypricelowhighv2-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByPriceLowHigh_V2() <NataliiaOliver>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/skincare/SkincareTest.java
testFaceSubmenuLink_NavigatesToFacePage() added
[TC] - https://trello.com/c/CEP1dTuy/102-tcmainskincareface-verify-that-the-face-submenu-link-from-the-skincare-dropdown-menu-is-clickable-and-navigates-to-face-page-nat
[AT] - https://trello.com/c/PpVPz4ib/105-atmainskincareface-testfacesubmenulinknavigatestofacepage-natalliaowl
=> [AT][Main][Skincare][Face] testFaceSubmenuLink_NavigatesToFacePage() <NatalliaOwl>

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/tests/books/PaperbackTest.java
Created testProductListSortByPriceHighLow_V2() with sortDoubleArray() and reverseDoubleArray() methods
[TC] - https://trello.com/c/40CAb6Zf/66-tcfunctionalmainnavmenubookssubmenu-dropdownpaperback-verify-product-sorting-by-price-high-to-low-nataliiaoliver
[AT] - https://trello.com/c/8e39zNSw/107-atfunctionalmainnavmenubookssubmenu-dropdownpaperback-testproductlistsortbypricehighlowv2-nataliiaoliver
=> [AT][Functional][Main][NavMenu][Books][Submenu dropdown][Paperback] testProductListSortByPriceHighLow_V2() <NataliiaOliver>

src/test/java/tests/skincare/SkincareTest.java
testEyesSubmenuLink_NavigatesToEyesPage() modified
[RF] - https://trello.com/c/SVOa3Lhs/108-rfmainnavmenuskincareeyes-testeyessubmenulinknavigatestoeyespage-natalliaowl
=> [RF][Main][NavMenu][Skincare][Eyes] testEyesSubmenuLink_NavigatesToEyesPage() <NatalliaOwl>

src/test/java/testData/ProjectConstants.java, src/test/java/tests/skincare/EyesTest.java
testEyesProductListSortedByAZ() added
[TC] - https://trello.com/c/y9UoUDq0/106-tcmainnavmenuskincaresubmenu-dropdowneyes-verify-that-products-are-sorted-by-name-in-alphabetic-order-from-a-to-z-when-clicking
[AT] - https://trello.com/c/HXasHls6/109-atmainnavmenuskincaresubmenu-dropdowneyes-testeyesproductlistsortedbyaz-natalliaowl
=> [AT]Main][NavMenu][Skincare][Submenu dropdown][Eyes] testEyesProductListSortedByAZ() <NatalliaOwl>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/men/BodyAndShowerTest.java
added testNavigatesToBodyAndShowerPage()
[US] - https://trello.com/c/pTPOiQ5T/92-usfunctionalmainshoespage-navigate-to-product-category-page-aleksandrakimovchg
[TC] - https://trello.com/c/QUSsfODC/91-tcmainnavmenumenbodyandshowerpage-navigate-to-body-shower-page-aleksandrakimovchg
[AT] - https://trello.com/c/kVC7Mzjf/110-atmainnavmenumenbodyandshowerpage-added-testnavigatestobodyandshowerpage-aleksandrakimovchg
=> [AT][Main][NavMenu][Men][BodyAndShowerPage] added testNavigatesToBodyAndShowerPage() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/men/BodyAndShowerTest.java
added testProductListSortByAZ()
[US] - https://trello.com/c/VbCIYI6c/75-usfunctionalmainnavmenucategorypagesubmenu-dropdownsubcategorypage-verify-product-sorting-in-alphabetic-order-from-a-to-z-and-in
[TC] - https://trello.com/c/WJEjObUR/114-tcmainnavmenumenbody-shower-verify-product-sorting-in-alphabetic-order-from-a-to-z-aleksandrakimovchg
[AT] - https://trello.com/c/74Rlm854/113-atmainnavmenumenbody-shower-testproductlistsortbyaz-aleksandrakimovchg
=> [AT][Main][NavMenu][Men][Body & Shower] testProductListSortByAZ() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/makeup/EyesTest.java
Four TestsEyesMakeupProductListSort added.
[TC][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Eyes] Verify if products sorted by name in alphabetical order from A to Z when click on Name A - Z dropdown Eyes submenu - https://trello.com/c/vapCSAbq/120-tcfunctionalmainnavmenumakeupsubmenudropdowneyes-verify-if-products-sorted-by-name-in-alphabetical-order-from-a-to-z-when-click
[AT][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Eyes]testEyesMakeupProductListSortByAZ - https://trello.com/c/MoQmQfzt/121-atfunctionalmainnavmenumakeupsubmenudropdowneyestesteyesmakeupproductlistsortbyazanzhelikabaa
[TC][Functional][Main][NavMenu][Makeup][SubmenuDropdown][Eyes] Verify if products sorted by price in ascending order when click on Price Low>High dropdown submenu - …
=> [AT][Functional][Main][NavMenu][Makeup][SubmenuDropdown[Eyes]FourTestsEyesMakeupProductListSort<AnzhelikaBaa>

src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/pages/product_list/ProductDescriptionPage.java
Grid Products strings and locators added
and methods added: clickAddToCart_GridProduct, getGridProduct_Name, getGridProduct1_Price
refactoring - static final String name (from final static)
[AT] - https://trello.com/c/vAEOCXLg/128-atfunctionalproducts-locators-and-methods-for-grid-products-verafes
=> [AT][Functional][Products] - Grid Products locators and methods added to ProductsPage

src/test/java/tests/home/HomeTest.java
testGetGridProduct1NameAndPrice_ID50 added
[AT] - https://trello.com/c/Tl682kqY/131-atfunctionalhomenameprice-testgetgridproduct1nameandpriceid50-verafes
[TC] - https://trello.com/c/qZFTdKmY/130-tcfunctionalhomenameprice-verify-name-and-price-for-product1-featured-verafes
=> [AT][Functional][Home][Name][Price] testGetGridProduct1NameAndPrice_ID50() <verafes>

src/test/java/pages/base_abstract/TablePage.java, src/test/java/tests/home/cart/CartTest.java, src/test/java/utils/TestUtils.java
testClickAddToCartButton_savesProduct1ToCart added - test verifies that, after a user clicks on AddToCart button, the product is saved in Cart, comparing its names and prices
additionally, the method capitalizeEachWordInString is added to TestUtils
[AT] - https://trello.com/c/Tl682kqY/131-atfunctionalhomenameprice-testgetgridproduct1nameandpriceid50-verafes
[TC] - https://trello.com/c/qZFTdKmY/130-tcfunctionalhomenameprice-verify-name-and-price-for-product1-featured-verafes
=> [AT][Functional][Home][Cart] testClickAddToCartButton_savesProduct1ToCart() <verafes>

src/test/java/tests/fragrance/WomenTest.java
testProductListSortByZA() added (Fragrance Menu Women Submenu)
[TC] - https://trello.com/c/d4Ow5skx/135-tcmainnavmenufragrancewomen-verify-product-sorting-in-reverse-alphabetic-order-from-z-to-a-nstzya
[AT] - https://trello.com/c/L7Mhhd4y/136-atmainnavmenufragrancewomen-testproductlistsortbyza-nstzya
=> [AT][Main][NavMenu][Fragrance][Women] testProductListSortByZA() <Nstzya>

src/test/java/pages/home/cart/CartPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/home/account/AccountLoginTest.java
testClickBothCheckoutButtons_navigatesToLoginPage_ifUserIsNotSignedIn() added
[TC] - https://trello.com/c/PvinbEme/137-tcfunctionalcartcheclout-clicking-both-checkout-buttons-navigate-to-login-page-if-user-is-not-signed-in-verafes
[AT] - https://trello.com/c/LSQNlj5M/138-atfunctionalcheckout-testclickbothcheckoutbuttonsnavigatestologinpageifuserisnotsignedin-verafes
=> [AT][Functional][Checkout] testClickBothCheckoutButtons_navigatesToLoginPage_ifUserIsNotSignedIn <verafes>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/men/FragranceSetsTest.java
added testNavigatesToFragranceSetsPage()
[US] - https://trello.com/c/pTPOiQ5T/92-usfunctionalmain-navigate-to-product-category-page-aleksandrakimovchg
[TC] - https://trello.com/c/FUj6KoTy/140-tcmainnavmenumenbodyandshowerpage-navigate-to-body-shower-page-aleksandrakimovchg
[AT] - https://trello.com/c/BMgMJLPd/139-atmainnavmenumenfragrancesetspage-added-testnavigatestofragrancesetspage-aleksandrakimovchg
=> [AT][Main][NavMenu][Men][FragranceSetsPage] added testNavigatesToFragranceSetsPage() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/home/CheckoutTest.java
testClickBothCheckoutButtons_navigatesToCheckOutPage_ifUserIsSignedIn() added
[AT] https://trello.com/c/SlH72yrz/144-atfunctionalcheckout-testclickbothcheckoutbuttonsnavigatestocheckoutpageifuserissignedin-verafes
[TC] https://trello.com/c/WbIJ3P60/145-tcfunctionalcartcheckout-clicking-both-checkout-buttons-navigate-to-checkout-page-if-user-is-signed-in-verafes
=> [AT][Functional][Checkout] testClickBothCheckoutButtons_navigatesToCheckoutPage_ifUserIsSignedIn()

src/test/java/base/BaseUtils.java
fixing ChromeOptions in BaseUtils
to get ChromeDriver working after the update
[ERR] https://trello.com/c/6kMoDHdx/147-errbaseutils-fix-chromeoptionsaddarguments-verafes
=> [ERR][BaseUtils] fix chromeOptions.addArguments <verafes>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/men/PreShaveAndShavingTest.java
added testNavigatesToPreShaveAndShavingPage()
[US] - https://trello.com/c/pTPOiQ5T/92-usfunctionalmain-navigate-to-product-category-page-aleksandrakimovchg
[TC] - https://trello.com/c/fF2eJkSx/151-tcmainnavmenumenbodyandshowerpage-navigate-to-body-shower-page-aleksandrakimovchg
[AT] - https://trello.com/c/j6xkrErC/150-atmainnavmenumenpreshaveandshavingpage-added-testnavigatestopreshaveandshavingpage-aleksandrakimovchg
=> [AT][Main][NavMenu][Men][PreShaveAndShavingPage] added testNavigatesToPreShaveAndShavingPage() <AleksandrAkimovChg>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/tests/my_account/MyAccountTest.java
testLoginLogoutSubmenuText added() added
[AT] https://trello.com/c/4xsEzFdr/152-atfunctionalmainlogoutsubmenu-testloginsubmenutextchangestologoutafterlogin-verafes
[TC] https://trello.com/c/TsVApfTn/153-tcfunctionalmainlogoutsubmenu-login-submenu-name-changes-to-logout-after-login-verafes
=> [AT][Functional][Main][LogoutSubmenu] testLoginSubmenuText_changesToLogoutAfterLogin() <verafes>

src/test/java/tests/MainTest.java
testTopMenuLinksNavigateToCorrespondingPages - fixed
(one step - to add a product to cart - added)
[RF] https://trello.com/c/ikYdDGtU/122-tcfunctionalmainnavmenumakeupsubmenudropdowneyes-verify-if-products-sorted-by-price-in-ascending-order-when-click-on-price-lowhi
=> [RF][Functional][Main][MyAccount] refactoring testTopMenuLinksNavigateToCorrespondingPages() <verafes>

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/makeup/FaceTest.java, src/test/java/tests/makeup/LipsTest.java
[TC] - https://trello.com/c/9n4Dl0Vt/155-tcfunctionalmainnavmenumakeupfacesubmenu-dropdown-verify-product-sorting-in-alphabetic-order-from-a-to-z-linavolovick
[AT] - https://trello.com/c/SuO9xDYa/156-atfunctionalmainnavmenumakeupface-testfacemakeupproductlistsortbyaz-linavolovick
added testFaceMakeupProductListSortByAZ() + locators + method clickFaceMakeupSubmenu()
=> testFaceMakeupProductListSortByAZ_linavolovick

src/test/java/tests/makeup/FaceTest.java, src/test/java/tests/makeup/LipsTest.java
[AT] - https://trello.com/c/Q4Q7qs57/159-atfunctionalmainnavmenumakeupface-testfacemakeupproductlistsortbyza-linavolovick
[TC] - https://trello.com/c/b1xthGsh/158-tcfunctionalmainnavmenumakeupfacesubmenu-dropdown-verify-product-sorting-in-reverse-alphabetic-order-from-z-to-a-linavolovick
added testFaceMakeupProductListSortByZA()
=> testFaceMakeupProductListSortByZA_linavolovick

src/test/java/pages/base_abstract/MainPage.java, src/test/java/testData/ProjectConstants.java, src/test/java/tests/my_account/LogoutTest.java
testClickLogoff_navigatesTo_LogoutPage() added
URLs to MyAccount and Logout pages added to ProjectConstants
Locator and method to get H1 text on any page added to MainPage
[TC] https://trello.com/c/WJDHNKfP/161-tcfunctionallogout-clicking-logooff-submenu-navigates-to-logout-page-verafes
[AT] https://trello.com/c/pWO9DDwM/162-atfunctionalmy-accountlogoff-testclicklogofflinknavigatestologoutpage-verafes
=> [AT][Functional][My Account][Logoff] testClickLogoffLink_navigatesTo_LogoutPage() <verafes>

src/test/java/testData/ProjectConstants.java, src/test/java/tests/makeup/FaceTest.java
[TC] - https://trello.com/c/pmxjRQZA/163-tcmainnavmenumakeupfacemakeuppage-navigate-to-facemakeup-page-linavolovick
[AT] - https://trello.com/c/KWSp57YU/164-atmainnavmenumakeupfacemakeuppagetestnavigatestofacemakeuppage-linavolovick
added testNavigateToFaceMakeupMenu
=> added testNavigateToFaceMakeupMenu<linavolovick>

src/test/java/tests/home/account/AccountLoginTest.java, src/test/java/tests/my_account/LogoutTest.java, src/test/java/tests/my_account/MyAccountTest.java
spelling mistakes fixed in the name of testClickLogOffLink_navigatesTo_LogoutPage
testLoginMenuCustomerText_changesAfterLogin() moved to MyAccountTest (because of asserts on MyAccountPage)
BaseLogIn() fixed -> now it returns myAccountPage instead of AccountLoginPage
[RF] - https://trello.com/c/86POe4oi/169-rfmainmyaccountpage-refactoring-code-tests-method-issues-verafes
=> [RF][Main][MyAccountPage] refactoring code, tests, method issues<verafes>

src/test/java/pages/my_account/MyAccountPage.java, src/test/java/testData/TestData.java, src/test/java/tests/my_account/MyAccountTest.java
testMyAccountSideMenuLinks_NavigateToCorrespondingPages added
[AT] -https://trello.com/c/mjGEvYhv/170-atmainmyaccountsidemenulinks-testmyaccoutsidemenumenulinksnavigatetocorrespondingpages-verafes
=> [AT][Main][MyAccount][SideMenu][Links] testMyAccoutSideMenuMenuLinks_NavigateToCorrespondingPages <verafes>

.github/workflows/ci.yml, pom.xml, src/test/java/network/CaptureNetworkTraffic.java, src/test/java/pages/apparel_and_accessories/TShirtsPage.java, src/test/java/pages/base_abstract/MainPage.java, src/test/java/pages/base_abstract/ProductsPage.java, src/test/java/pages/hair_care/ConditionerPage.java, src/test/java/pages/hair_care/SeaweedConditionerProductPage.java, src/test/java/pages/product_list/DescriptionPage.java, src/test/java/pages/product_list/NewLadies_Sandals_ID116_Page.java, src/test/java/pages/product_list/ProductDescriptionPage.java, src/test/java/pages/product_list/WomensStilettoSandals_ID118_Page.java, src/test/java/pages/product_list/benefit/BenefitBellaBambaPage.java, src/test/java/pages/product_list/benefit/BenefitGirlMeetsPearlPage.java, src/test/java/pages/product_list/books/AudioCDNewFrenchWithEasePage.java, src/test/java/pages/product_list/books/PaperbackAllegiantByVeronicaRothPage.java, src/test/java/pages/product_list/bvlgari/BvlgariPourHommeEauDeToilettePage.java, src/test/java/pages/product_list/calvin_klein/CKOneShockForHimDeodorantPage.java, src/test/java/pages/product_list/calvin_klein/CKSecretObsessionPerfumePage.java, src/test/java/pages/product_list/dove/DoveMenCareCleanComfortDeodorantPage.java, src/test/java/pages/product_list/giorgio_armani/GiorgioArmaniCodePourFemmePage.java, src/test/java/pages/product_list/gucci/GucciGuiltyPage.java, src/test/java/pages/product_list/lancome/LancomeTropiquesMineraleLooseBronzerPage.java, src/test/java/pages/product_list/mac/MacSkinsheenBronzerStickPage.java, src/test/java/pages/product_list/pantene/PanteneCurlsToStraightShampooPage.java, src/test/java/pages/product_list/pantene/PanteneHighlightingExpressionsPage.java, src/test/java/pages/product_list/sephora/SephoraSeaweedConditionerPage.java, src/test/java/tests/home/cart/SuccessTest.java
testSuccessInscriptionOnTheSuccessPage() not finished
=> testSuccessInscriptionOnTheSuccessPage() not finished
